######################################################################
# Automatically generated by qmake (3.0) ?? 9? 28 16:14:19 2014
######################################################################

QT       += core gui


greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = dialogs
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h \
    sansdialog.h
FORMS += mainwindow.ui \
    sansdialog.ui
SOURCES += main.cpp mainwindow.cpp \
    sansdialog.cpp
